apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangodraws-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django-docker
          image: localhost:32000/django-docker:registry
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: djangodraws-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001